version: '3'
services:
  db:
    image: 'mariadb:latest'
    ports:
      - '3306:3306'
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:   