version: '3'
services:
  wp:
    depends_on:
     - db
    image: 'wordpress:latest'
    ports:
     - '443:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: 192.168.1.151:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
        - wp_data:/var/www/html    

volumes:
  wp_data:
